# Generated by Django 5.1.6 on 2025-02-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='address',
            field=models.TextField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
