# Generated by Django 5.1.6 on 2025-03-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_remove_jobseeker_location_remove_jobseeker_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Pending', 'Pending'), ('Approved', 'Approved')], default='Incomplete', max_length=20),
        ),
    ]
