# Generated by Django 5.1.6 on 2025-03-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0008_jobseeker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='status',
        ),
    ]
