# Generated by Django 5.1.6 on 2025-04-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0010_alter_jobapplication_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
