# Generated by Django 5.1.6 on 2025-04-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0011_delete_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='education',
            field=models.CharField(max_length=290),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
