# Generated by Django 5.1.6 on 2025-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0012_jobapplication_message_alter_jobseeker_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
