# Generated by Django 5.1.6 on 2025-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('register_recruiter', 'Recruiter'), ('register_applicant', 'Applicant')], default='register_applicant', max_length=50),
        ),
    ]
