# Generated by Django 5.1.6 on 2025-02-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('register_recruiter', 'Recruiter'), ('register_applicant', 'Applicant')], default='Applicant', max_length=50),
        ),
    ]
