# Generated by Django 5.1.6 on 2025-03-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'role')},
        ),
    ]
