# Generated by Django 5.1.6 on 2025-02-20 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.PositiveIntegerField(default=0, help_text='Experience in years'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', to='jobs.skill'),
        ),
    ]
