# Generated by Django 5.1.6 on 2025-03-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0009_remove_jobseeker_status'),
        ('jobs', '0002_skill_job_company_name_job_company_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('full_name', models.CharField(default='Unknown', max_length=255)),
                ('address', models.TextField(default='Not Provided', max_length=255)),
                ('skills', models.TextField(blank=True, null=True)),
                ('education', models.TextField(default='Not Provided')),
                ('experience', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('job_seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseeker')),
            ],
        ),
    ]
