# Generated by Django 5.1.6 on 2025-04-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_savedjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_at']},
        ),
    ]
