# Generated by Django 5.1.6 on 2025-04-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_established_year'),
        ('jobs', '0007_alter_job_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.PositiveIntegerField(choices=[('0-2', '0-2 Years'), ('2-4', '2-4 Years'), ('4-6', '4-6 Years'), ('6-8', '6-8 Years'), ('8+', '8+ Years')], help_text='Experience in years'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
