# Generated by Django 5.1.6 on 2025-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_company_alter_job_experience_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
