# Generated by Django 5.1.6 on 2025-03-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
