# Generated by Django 5.1.6 on 2025-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_established_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('50-200', '50-200 Employees'), ('200-500', '200-500 Employees'), ('500+', '500+ Employees')], max_length=200),
        ),
    ]
