# Generated by Django 5.1.6 on 2025-04-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resumes/photos')),
                ('dob', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('adress', models.TextField(blank=True, max_length=500, null=True)),
                ('matriculation', models.CharField(blank=True, max_length=300, null=True)),
                ('intermediate', models.CharField(blank=True, max_length=300, null=True)),
                ('graduation', models.CharField(blank=True, max_length=300, null=True)),
                ('postgraduation', models.CharField(blank=True, max_length=300, null=True)),
                ('skills', models.TextField(blank=True, max_length=500, null=True)),
                ('experience', models.TextField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('projects', models.TextField(blank=True, max_length=600, null=True)),
                ('additional_qualifications', models.TextField(blank=True, max_length=600, null=True)),
                ('languages', models.TextField(blank=True, max_length=500, null=True)),
                ('hobbies', models.TextField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
